import '../../features/customer/domain/entities/customer.dart';
import '../../features/vehicle/domain/entities/vehicle.dart';
import '../../features/work_order/domain/entities/work_order.dart';
import '../../features/work_order/domain/entities/work_order_service.dart';
import '../../features/work_order/domain/entities/work_order_product.dart';
import '../../features/service/domain/entities/service_entity.dart';
import '../../features/product/domain/entities/product.dart';

class DummyData {
  // Dummy Customers
  static final List<Customer> customers = [
    const Customer(
      id: 'cust-001',
      name: 'Budi Santoso',
      phoneNumber: '081234567890',
      email: 'budi.santoso@email.com',
    ),
    const Customer(
      id: 'cust-002',
      name: 'Siti Aminah',
      phoneNumber: '081234567891',
      email: 'siti.aminah@email.com',
    ),
    const Customer(
      id: 'cust-003',
      name: 'Agus Wijaya',
      phoneNumber: '081234567892',
      email: 'agus.wijaya@email.com',
    ),
    const Customer(
      id: 'cust-004',
      name: 'Dewi Lestari',
      phoneNumber: '081234567893',
      email: 'dewi.lestari@email.com',
    ),
    const Customer(
      id: 'cust-005',
      name: 'Rudi Hartono',
      phoneNumber: '081234567894',
      email: 'rudi.hartono@email.com',
    ),
    const Customer(
      id: 'cust-006',
      name: 'Maya Kusuma',
      phoneNumber: '081234567895',
      email: 'maya.kusuma@email.com',
    ),
    const Customer(
      id: 'cust-007',
      name: 'Eko Prasetyo',
      phoneNumber: '081234567896',
      email: 'eko.prasetyo@email.com',
    ),
    const Customer(
      id: 'cust-008',
      name: 'Nina Sari',
      phoneNumber: '081234567897',
      email: 'nina.sari@email.com',
    ),
  ];

  // Dummy Vehicles
  static final List<Vehicle> vehicles = [
    const Vehicle(
      id: 'veh-001',
      licensePlate: 'B 1234 ABC',
      vehicleBrand: 'Honda',
      vehicleColor: 'Merah',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'Beat',
    ),
    const Vehicle(
      id: 'veh-002',
      licensePlate: 'B 5678 DEF',
      vehicleBrand: 'Yamaha',
      vehicleColor: 'Hitam',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'Vario 125',
    ),
    const Vehicle(
      id: 'veh-003',
      licensePlate: 'B 9012 GHI',
      vehicleBrand: 'Suzuki',
      vehicleColor: 'Putih',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'Nex II',
    ),
    const Vehicle(
      id: 'veh-004',
      licensePlate: 'B 3456 JKL',
      vehicleBrand: 'Honda',
      vehicleColor: 'Biru',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'Scoopy',
    ),
    const Vehicle(
      id: 'veh-005',
      licensePlate: 'B 7890 MNO',
      vehicleBrand: 'Yamaha',
      vehicleColor: 'Silver',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'Aerox',
    ),
    const Vehicle(
      id: 'veh-006',
      licensePlate: 'B 2345 PQR',
      vehicleBrand: 'Honda',
      vehicleColor: 'Merah Maroon',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'PCX 160',
    ),
    const Vehicle(
      id: 'veh-007',
      licensePlate: 'B 6789 STU',
      vehicleBrand: 'Suzuki',
      vehicleColor: 'Hijau',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'Satria',
    ),
    const Vehicle(
      id: 'veh-008',
      licensePlate: 'B 1357 VWX',
      vehicleBrand: 'Yamaha',
      vehicleColor: 'Kuning',
      vehicleCategory: 'Motor',
      vehicleSpecs: 'NMAX',
    ),
  ];

  // Dummy Services
  static const List<ServiceEntity> services = [
    ServiceEntity(
      id: 'svc-001',
      name: 'Cuci Motor Reguler',
      description: 'Cuci motor standar dengan sabun dan air',
      price: 15000,
      imageUrl: '',
      isDefault: true,
      isFavorite: false,
      type: 'Cuci',
      isActive: true,
    ),
    ServiceEntity(
      id: 'svc-002',
      name: 'Cuci Motor Premium',
      description: 'Cuci motor dengan wax dan poles',
      price: 25000,
      imageUrl: '',
      isDefault: false,
      isFavorite: true,
      type: 'Cuci',
      isActive: true,
    ),
    ServiceEntity(
      id: 'svc-003',
      name: 'Poles Body',
      description: 'Poles body motor hingga mengkilap',
      price: 30000,
      imageUrl: '',
      isDefault: false,
      isFavorite: true,
      type: 'Poles',
      isActive: true,
    ),
    ServiceEntity(
      id: 'svc-004',
      name: 'Wax & Coating',
      description: 'Aplikasi wax untuk perlindungan cat',
      price: 40000,
      imageUrl: '',
      isDefault: false,
      isFavorite: false,
      type: 'Coating',
      isActive: true,
    ),
    ServiceEntity(
      id: 'svc-005',
      name: 'Detailing Lengkap',
      description: 'Cuci, poles, wax, dan detailing interior',
      price: 75000,
      imageUrl: '',
      isDefault: false,
      isFavorite: true,
      type: 'Detailing',
      isActive: true,
    ),
  ];

  // Dummy Products (F&B)
  static const List<Product> products = [
    Product(
      id: 'prod-001',
      name: 'Es Teh Manis',
      description: 'Teh manis dingin',
      price: 5000,
      imageUrl: '',
      type: 'Minuman',
      stock: 100,
      isAvailable: true,
    ),
    Product(
      id: 'prod-002',
      name: 'Kopi Hitam',
      description: 'Kopi hitam panas',
      price: 8000,
      imageUrl: '',
      type: 'Minuman',
      stock: 100,
      isAvailable: true,
    ),
    Product(
      id: 'prod-003',
      name: 'Air Mineral',
      description: 'Air mineral kemasan',
      price: 3000,
      imageUrl: '',
      type: 'Minuman',
      stock: 100,
      isAvailable: true,
    ),
    Product(
      id: 'prod-004',
      name: 'Gorengan',
      description: 'Gorengan pisang/tempe/tahu',
      price: 2000,
      imageUrl: '',
      type: 'Makanan',
      stock: 50,
      isAvailable: true,
    ),
    Product(
      id: 'prod-005',
      name: 'Nasi Goreng',
      description: 'Nasi goreng spesial',
      price: 15000,
      imageUrl: '',
      type: 'Makanan',
      stock: 20,
      isAvailable: true,
    ),
  ];

  // Dummy Work Orders
  static List<WorkOrder> getWorkOrders() {
    final now = DateTime.now();

    return [
      // Work Order 1 - Queued
      WorkOrder(
        id: 'wo-001',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-001',
        customerId: 'cust-001',
        vehicleDataId: 'veh-001',
        queueNumber: '1',
        estimatedTime: '30 menit',
        status: 'queued',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 45000,
        services: [
          WorkOrderService(
            id: 'wos-001',
            workOrderId: 'wo-001',
            serviceId: 'svc-002',
            quantity: 1,
            priceAtOrder: 25000,
            subtotal: 25000,
            service: services[1],
          ),
          WorkOrderService(
            id: 'wos-002',
            workOrderId: 'wo-001',
            serviceId: 'svc-003',
            quantity: 1,
            priceAtOrder: 30000,
            subtotal: 30000,
            service: services[2],
          ),
        ],
        products: [
          WorkOrderProduct(
            id: 'wop-001',
            workOrderId: 'wo-001',
            productId: 'prod-001',
            quantity: 2,
            priceAtOrder: 5000,
            subtotal: 10000,
            product: products[0],
          ),
        ],
        createdAt: now.subtract(const Duration(minutes: 10)),
        updatedAt: now.subtract(const Duration(minutes: 10)),
        completedAt: null,
      ),

      // Work Order 2 - Washing
      WorkOrder(
        id: 'wo-002',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-002',
        customerId: 'cust-002',
        vehicleDataId: 'veh-002',
        queueNumber: '2',
        estimatedTime: '20 menit',
        status: 'washing',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 20000,
        services: [
          WorkOrderService(
            id: 'wos-003',
            workOrderId: 'wo-002',
            serviceId: 'svc-001',
            quantity: 1,
            priceAtOrder: 15000,
            subtotal: 15000,
            service: services[0],
          ),
        ],
        products: [
          WorkOrderProduct(
            id: 'wop-002',
            workOrderId: 'wo-002',
            productId: 'prod-003',
            quantity: 1,
            priceAtOrder: 3000,
            subtotal: 3000,
            product: products[2],
          ),
        ],
        createdAt: now.subtract(const Duration(minutes: 25)),
        updatedAt: now.subtract(const Duration(minutes: 5)),
        completedAt: null,
      ),

      // Work Order 3 - Drying
      WorkOrder(
        id: 'wo-003',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-003',
        customerId: 'cust-003',
        vehicleDataId: 'veh-003',
        queueNumber: '3',
        estimatedTime: '45 menit',
        status: 'drying',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 70000,
        services: [
          WorkOrderService(
            id: 'wos-004',
            workOrderId: 'wo-003',
            serviceId: 'svc-004',
            quantity: 1,
            priceAtOrder: 40000,
            subtotal: 40000,
            service: services[3],
          ),
        ],
        products: [
          WorkOrderProduct(
            id: 'wop-003',
            workOrderId: 'wo-003',
            productId: 'prod-002',
            quantity: 1,
            priceAtOrder: 8000,
            subtotal: 8000,
            product: products[1],
          ),
          WorkOrderProduct(
            id: 'wop-004',
            workOrderId: 'wo-003',
            productId: 'prod-004',
            quantity: 3,
            priceAtOrder: 2000,
            subtotal: 6000,
            product: products[3],
          ),
        ],
        createdAt: now.subtract(const Duration(minutes: 40)),
        updatedAt: now.subtract(const Duration(minutes: 3)),
        completedAt: null,
      ),

      // Work Order 4 - Inspection
      WorkOrder(
        id: 'wo-004',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-004',
        customerId: 'cust-004',
        vehicleDataId: 'veh-004',
        queueNumber: '4',
        estimatedTime: '90 menit',
        status: 'inspection',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 98000,
        services: [
          WorkOrderService(
            id: 'wos-005',
            workOrderId: 'wo-004',
            serviceId: 'svc-005',
            quantity: 1,
            priceAtOrder: 75000,
            subtotal: 75000,
            service: services[4],
          ),
        ],
        products: [
          WorkOrderProduct(
            id: 'wop-005',
            workOrderId: 'wo-004',
            productId: 'prod-001',
            quantity: 1,
            priceAtOrder: 5000,
            subtotal: 5000,
            product: products[0],
          ),
          WorkOrderProduct(
            id: 'wop-006',
            workOrderId: 'wo-004',
            productId: 'prod-005',
            quantity: 1,
            priceAtOrder: 15000,
            subtotal: 15000,
            product: products[4],
          ),
        ],
        createdAt: now.subtract(const Duration(hours: 1)),
        updatedAt: now.subtract(const Duration(minutes: 2)),
        completedAt: null,
      ),

      // Work Order 5 - Completed
      WorkOrder(
        id: 'wo-005',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-005',
        customerId: 'cust-005',
        vehicleDataId: 'veh-005',
        queueNumber: '5',
        estimatedTime: '30 menit',
        status: 'completed',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 55000,
        services: [
          WorkOrderService(
            id: 'wos-006',
            workOrderId: 'wo-005',
            serviceId: 'svc-002',
            quantity: 1,
            priceAtOrder: 25000,
            subtotal: 25000,
            service: services[1],
          ),
          WorkOrderService(
            id: 'wos-007',
            workOrderId: 'wo-005',
            serviceId: 'svc-003',
            quantity: 1,
            priceAtOrder: 30000,
            subtotal: 30000,
            service: services[2],
          ),
        ],
        products: [],
        createdAt: now.subtract(const Duration(hours: 1, minutes: 30)),
        updatedAt: now.subtract(const Duration(minutes: 1)),
        completedAt: now.subtract(const Duration(minutes: 1)),
      ),

      // Work Order 6 - Paid
      WorkOrder(
        id: 'wo-006',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-006',
        customerId: 'cust-006',
        vehicleDataId: 'veh-006',
        queueNumber: '6',
        estimatedTime: '20 menit',
        status: 'paid',
        paymentStatus: 'paid',
        paymentMethod: 'cash',
        paidAmount: 18000,
        totalPrice: 18000,
        services: [
          WorkOrderService(
            id: 'wos-008',
            workOrderId: 'wo-006',
            serviceId: 'svc-001',
            quantity: 1,
            priceAtOrder: 15000,
            subtotal: 15000,
            service: services[0],
          ),
        ],
        products: [
          WorkOrderProduct(
            id: 'wop-007',
            workOrderId: 'wo-006',
            productId: 'prod-003',
            quantity: 1,
            priceAtOrder: 3000,
            subtotal: 3000,
            product: products[2],
          ),
        ],
        createdAt: now.subtract(const Duration(hours: 2)),
        updatedAt: now.subtract(const Duration(hours: 1, minutes: 30)),
        completedAt: now.subtract(const Duration(hours: 1, minutes: 30)),
      ),

      // Work Order 7 - Queued
      WorkOrder(
        id: 'wo-007',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-007',
        customerId: 'cust-007',
        vehicleDataId: 'veh-007',
        queueNumber: '7',
        estimatedTime: '45 menit',
        status: 'queued',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 80000,
        services: [
          WorkOrderService(
            id: 'wos-009',
            workOrderId: 'wo-007',
            serviceId: 'svc-004',
            quantity: 1,
            priceAtOrder: 40000,
            subtotal: 40000,
            service: services[3],
          ),
          WorkOrderService(
            id: 'wos-010',
            workOrderId: 'wo-007',
            serviceId: 'svc-002',
            quantity: 1,
            priceAtOrder: 25000,
            subtotal: 25000,
            service: services[1],
          ),
        ],
        products: [
          WorkOrderProduct(
            id: 'wop-008',
            workOrderId: 'wo-007',
            productId: 'prod-001',
            quantity: 2,
            priceAtOrder: 5000,
            subtotal: 10000,
            product: products[0],
          ),
          WorkOrderProduct(
            id: 'wop-009',
            workOrderId: 'wo-007',
            productId: 'prod-002',
            quantity: 1,
            priceAtOrder: 8000,
            subtotal: 8000,
            product: products[1],
          ),
        ],
        createdAt: now.subtract(const Duration(minutes: 5)),
        updatedAt: now.subtract(const Duration(minutes: 5)),
        completedAt: null,
      ),

      // Work Order 8 - Queued
      WorkOrder(
        id: 'wo-008',
        workOrderCode: 'WO-${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}-008',
        customerId: 'cust-008',
        vehicleDataId: 'veh-008',
        queueNumber: '8',
        estimatedTime: '20 menit',
        status: 'queued',
        paymentStatus: 'pending',
        paymentMethod: null,
        paidAmount: 0,
        totalPrice: 15000,
        services: [
          WorkOrderService(
            id: 'wos-011',
            workOrderId: 'wo-008',
            serviceId: 'svc-001',
            quantity: 1,
            priceAtOrder: 15000,
            subtotal: 15000,
            service: services[0],
          ),
        ],
        products: [],
        createdAt: now.subtract(const Duration(minutes: 2)),
        updatedAt: now.subtract(const Duration(minutes: 2)),
        completedAt: null,
      ),
    ];
  }
}
