import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import '../../../../core/error/failures.dart';
import '../../../../core/usecase/usecase.dart';
import '../entities/customer.dart';
import '../repositories/customer_repository.dart';

class CreateCustomer implements UseCase<Customer, CreateCustomerParams> {
  final CustomerRepository repository;

  CreateCustomer(this.repository);

  @override
  Future<Either<Failure, Customer>> call(CreateCustomerParams params) async {
    // For creation, ID might be empty or generated by backend
    return await repository.createCustomer(Customer(
      id: '', // Backend generates ID
      name: params.name,
      phoneNumber: params.phoneNumber,
      email: params.email,
    ));
  }
}

class CreateCustomerParams extends Equatable {
  final String name;
  final String phoneNumber;
  final String email;

  const CreateCustomerParams({
    required this.name,
    required this.phoneNumber,
    required this.email,
  });

  @override
  List<Object> get props => [name, phoneNumber, email];
}
